# Generated by Django 5.2 on 2025-04-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinExpenses',
            fields=[
                ('fin_expenses_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('user_inserted', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('user_updated', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fin_expenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinIncome',
            fields=[
                ('fin_income_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('user_inserted', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('user_updated', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fin_income',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefCategory',
            fields=[
                ('ref_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rashod', models.IntegerField(db_comment='0 - NE; -1 - DA')),
                ('prihod', models.IntegerField(db_comment='0 - NE; -1 - DA')),
                ('user_inserted', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('user_updated', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ref_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefCurrency',
            fields=[
                ('ref_currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('user_inserted', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('user_updated', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ref_currency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefMeansOfPayment',
            fields=[
                ('ref_means_of_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('user_inserted', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('user_updated', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ref_means_of_payment',
                'managed': False,
            },
        ),
    ]
